# syntax = edrevo/dockerfile-plus
INCLUDE+ Dockerfile.export-model

# install exported model into tensorflow/serving image
FROM tensorflow/serving:2.8.0
COPY --from=export_model /build/model ./models/model
