
name: CI

on: [push]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build CPU image
        run: docker build . -f Dockerfile.cpu
      - name: build GPU image
        run: docker build . -f Dockerfile.gpu